/**
 * Build-time generator: samples a lat/lng grid, keeps points that fall inside
 * land polygons, and emits a flat array. Runs once, offline — the app pays
 * zero runtime cost for the dot-matrix globe.
 *
 *   npx tsx --tsconfig tsconfig.test.json scripts/generateLandDots.ts
 */
import { writeFileSync } from 'node:fs';
import * as topojson from 'topojson-client';
import world from 'world-atlas/land-110m.json';
import { collectRingsFromGeoJson } from '../lib/geo/landmass';

import { fileURLToPath } from 'node:url';
import path from 'node:path';


type Ring = ReadonlyArray<readonly [number, number]>;

/** Standard ray-casting point-in-polygon, in lat/lng space. */
function inRing(lng: number, lat: number, ring: Ring): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const xi = ring[i]![0], yi = ring[i]![1];
    const xj = ring[j]![0], yj = ring[j]![1];
    if (yi > lat !== yj > lat && lng < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) {
      inside = !inside;
    }
  }
  return inside;
}

const land = topojson.feature(world as never, (world as never as { objects: { land: never } }).objects.land);
const rings = collectRingsFromGeoJson(land);

// Bounding boxes make the inner loop ~20x cheaper.
const boxes = rings.map((r) => {
  let minX = 180, maxX = -180, minY = 90, maxY = -90;
  for (const [x, y] of r) {
    if (x < minX) minX = x; if (x > maxX) maxX = x;
    if (y < minY) minY = y; if (y > maxY) maxY = y;
  }
  return { minX, maxX, minY, maxY };
});

/**
 * Equal-area sampling: longitude step scales by 1/cos(lat) so dots don't
 * bunch up at the poles. Without this the Arctic turns into a solid blob.
 */
const LAT_STEP = 1.6;
const TARGET_SPACING = 1.6;
const out: number[] = [];
const t0 = Date.now();

for (let lat = -85; lat <= 85; lat += LAT_STEP) {
  const cos = Math.cos((lat * Math.PI) / 180);
  const lngStep = Math.min(12, TARGET_SPACING / Math.max(0.08, cos));
  for (let lng = -180; lng < 180; lng += lngStep) {
    let inside = false;
    for (let i = 0; i < rings.length; i++) {
      const b = boxes[i]!;
      if (lng < b.minX || lng > b.maxX || lat < b.minY || lat > b.maxY) continue;
      if (inRing(lng, lat, rings[i]!)) inside = !inside;
    }
    if (inside) out.push(Math.round(lat * 100) / 100, Math.round(lng * 100) / 100);
  }
}

const body = `// GENERATED by scripts/generateLandDots.ts — do not edit by hand.
// ${out.length / 2} land sample points, lat/lng interleaved.
export const LAND_DOTS = new Float32Array([
${out.join(',')}
]);
`;
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outputPath = path.resolve(__dirname, '../lib/geo/landDots.generated.ts');

writeFileSync(outputPath, body);
console.log(`dots=${out.length / 2} in ${Date.now() - t0}ms -> /lib/geo/landDots.generated.ts`);